### 1. Registrar un nuevo usuario (Solo si no existe)
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "sebastiana@gmail.com",
    "password": "1234567890"
}

### -------------------------------------------------------

### 2. Login para obtener el TOKEN
# NOTA: Copia el valor de "Token" que sale en la respuesta.
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "alixiscaco@gmail.com",
    "password": "1234567890"
}

### -------------------------------------------------------
### TOKEN DE USUARIO
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJveWVjdG8tYWR2YWloIiwiYXVkIjoicHJveWVjdG8tYWR2YWloIiwiYXV0aF90aW1lIjoxNzc1NDgwMjQ1LCJ1c2VyX2lkIjoiRjUwaEJnUHJnblR1b0hGa2FEeW1zZXhWWk9nMiIsInN1YiI6IkY1MGhCZ1ByZ25UdW9IRmthRHltc2V4VlpPZzIiLCJpYXQiOjE3NzU0ODAyNDUsImV4cCI6MTc3NTQ4Mzg0NSwiZW1haWwiOiJhbGl4aXNjYWNvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbGl4aXNjYWNvQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gmQ_COIL659efEBfvrk5SFoiPfdhqgOuIlyzB9r6xpUBEsuk4uWPGZ0MgG9mcLXGCB6DwDdoRXj8E23KsdDLxgNfjVLLRfWBCG5Zv2oz3c41yT6Hsuepn-jO8XSf6kbc9iyIlHP1Sgfm3DNgraFdBWU_u58rYzyq-ye__f7ZIjqIFhzwHKxGQsnF_FGivVyvsfJuUeZCNyyyHe8UPT0NKcRLWxXfvBRvQvhY1P_r-oApxHYnhQHRVT0_gkcE0-NGOHxl7yoOOe1K_lmhlWJ9SBY1Cd333c9D_AybgBsmJN86Y6AVP08wAee6VV2B-cH0qtpHZx2sAxazcdmZQG1YAA

### 3. Crear un nuevo evento
POST http://127.0.0.1:8000/api/eventos/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "Evento de prueba (notificaiiiiiiiicion232552222)",
    "descripcion": "Probando mi API con las nuevas vistas corregidas este sera para eliminar y probar",
    "fecha": "2026-03-30T10:00:00Z",
    "lugar": "Centro de Mosquera "
}

### -------------------------------------------------------

### 4. Listar mis eventos (GET)
# Si te da error de "index", revisa la terminal de Django y haz clic en el link de Google.
GET http://127.0.0.1:8000/api/eventos/?Limit=5
Authorization: Bearer {{token}}

### -------------------------------------------------------

### 5. Actualizar un evento (PUT)
# RECUERDA: Cambia "ID_DEL_EVENTO" por un ID real que obtuviste en el paso 4.
PUT http://127.0.0.1:8000/api/eventos/bcKfY8FqiIRZKTPRMf1G/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "Evento Actualizado",
    "descripcion": "Ya funciona el PUT probando actualizar un evento",
    "fecha": "2026-03-31T15:00:00Z",
    "lugar": "Villa Olímpica"
}

### -------------------------------------------------------

### 6. Eliminar un evento (DELETE)
DELETE http://127.0.0.1:8000/api/eventos/i6u7RJzab309lLjqFQw3/
Authorization: Bearer {{token}}

### -------------------------------------------------------

### 7. Subir foto de perfil
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer {{token}}

imagen=@avatar.jpg


###
POST http://127.0.0.1:8000/api/enviar-tareas/
Content-Type: application/json
Authorization: Bearer TU_TOKEN

{
  "correo": "destino@gmail.com"
}


### estadisticas
GET http://127.0.0.1:8000/api/eventos/estadisticas/
Authorization: Bearer {{token}}