### 1. Registrar un nuevo usuario (Solo si no existe)
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "alixiscaco@gmail.com",
    "password": "1234567890"
}

### -------------------------------------------------------

### 2. Login para obtener el TOKEN
# NOTA: Copia el valor de "Token" que sale en la respuesta.
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "alixiscaco@gmail.com",
    "password": "1234567890"
}

### -------------------------------------------------------
### TOKEN DE USUARIO
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJveWVjdG8tYWR2YWloIiwiYXVkIjoicHJveWVjdG8tYWR2YWloIiwiYXV0aF90aW1lIjoxNzczNjc2OTgwLCJ1c2VyX2lkIjoiRjUwaEJnUHJnblR1b0hGa2FEeW1zZXhWWk9nMiIsInN1YiI6IkY1MGhCZ1ByZ25UdW9IRmthRHltc2V4VlpPZzIiLCJpYXQiOjE3NzM2NzY5ODAsImV4cCI6MTc3MzY4MDU4MCwiZW1haWwiOiJhbGl4aXNjYWNvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbGl4aXNjYWNvQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Vdg3U17bXgq07V8DIrJUdbVqePwXjNBJ-WTbNHXH3TlIs-nXh9PeKX6_XmyzwSE-VLICNLCLDWeq7cFJ3qf3sSDM-Ba4w_rWc4Uio5LaecM91bWOD3v-0yRO37FrlBT0XK3UTNzawMS0i_fiFKm8c0q15TbokfzMjPPezWJSgw-wi2uCu--p0imI60hCYKeNv_TozvZVGqi0n94dqzEvh9sNAUzEhATlXIqTQp-06ZGP8d0-8BS2bPZrFIGgHBU7kkOkTMyciG7OkcD2juWIxE71pK8ElfJat9M24vUkA8zp_G3KL69BtmKcn8DRF1DRp0L60yDU5BwZv_1PkGMXVA

### 3. Crear un nuevo evento
POST http://127.0.0.1:8000/api/eventos/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "Evento de prueba (delete)",
    "descripcion": "Probando mi API con las nuevas vistas corregidas este sera para eliminar",
    "fecha": "2026-03-30T10:00:00Z",
    "lugar": "Centro de Mosquera"
}

### -------------------------------------------------------

### 4. Listar mis eventos (GET)
# Si te da error de "index", revisa la terminal de Django y haz clic en el link de Google.
GET http://127.0.0.1:8000/api/eventos/?Limit=5
Authorization: Bearer {{token}}

### -------------------------------------------------------

### 5. Actualizar un evento (PUT)
# RECUERDA: Cambia "ID_DEL_EVENTO" por un ID real que obtuviste en el paso 4.
PUT http://127.0.0.1:8000/api/eventos/bcKfY8FqiIRZKTPRMf1G/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "Evento Actualizado",
    "descripcion": "Ya funciona el PUT probando actualizar un evento",
    "fecha": "2026-03-31T15:00:00Z",
    "lugar": "Villa Olímpica"
}

### -------------------------------------------------------

### 6. Eliminar un evento (DELETE)
DELETE http://127.0.0.1:8000/api/eventos/i6u7RJzab309lLjqFQw3/
Authorization: Bearer {{token}}

### -------------------------------------------------------

### 7. Subir foto de perfil
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer {{token}}

imagen=@avatar.jpg